language: go
go:
  - 1.2
  - 1.2.1
  - tip
install:
  - go get code.google.com/p/go.tools/cmd/cover
  - go get github.com/JustAdam/goveralls
  - export PATH=$PATH:$HOME/gopath/bin/
script:
  - go get -d -v ./... && go build -v ./...
  - go test -covermode=count -coverprofile=profile.cov
after_success:
  - goveralls -coverprofile=profile.cov -service=travis-ci
